# Generated by Django 4.2 on 2025-07-27 19:53

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'this username already exist'}, help_text='Enter at least 6 character or number for your username', max_length=25, unique=True, validators=[django.core.validators.RegexValidator(message='Your username must be contain at least 6 character or number', regex='^(?=.*[a-zA-Z])(?=.*\\d).{6,}$')], verbose_name='username')),
                ('phone_number', models.BigIntegerField(unique=True, validators=[django.core.validators.RegexValidator(message='Your phone number mast be unique and valid', regex='^989[0-3]\\d{8}$')], verbose_name='phone number')),
                ('full_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='full name')),
                ('email', models.CharField(blank=True, max_length=40, null=True, verbose_name='email')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is staff')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('data_joined', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date join')),
                ('last_seen', models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 27, 19, 53, 49, 421908, tzinfo=datetime.timezone.utc), null=True, verbose_name='last seen')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserPofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d/', verbose_name='avatar')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='birthday')),
                ('bio', models.TextField(blank=True, verbose_name='bio')),
                ('nick_name', models.CharField(blank=True, max_length=20, verbose_name='nick name')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'users profile',
                'db_table': 'users profile',
            },
        ),
    ]
