# Generated by Django 4.2 on 2025-07-25 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'unique': 'this title already exist!'}, max_length=20, unique=True, verbose_name='title')),
                ('avatar', models.ImageField(upload_to='categories/', verbose_name='avatar')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'error': 'this product already exist'}, max_length=30, unique=True, verbose_name='title')),
                ('count', models.IntegerField(verbose_name='count')),
                ('avatar', models.ImageField(upload_to='products/', verbose_name='avatar')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_enable', models.BooleanField(default=True, verbose_name='is exists')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'products',
            },
        ),
    ]
